// Generated by CoffeeScript 1.6.3
/*
# test for taggabler_via_redis
*/


(function() {
  var REDIS_CLIENT, Taggable, should, thingTagger;

  should = require("should");

  Taggable = require("../taggabler_via_redis");

  REDIS_CLIENT = null;

  thingTagger = null;

  describe("basic find tests", function() {
    before(function(done) {
      var redis;
      redis = require("redis");
      REDIS_CLIENT = redis.createClient();
      REDIS_CLIENT.flushall();
      thingTagger = new Taggable({
        taggable: "thing",
        redisClient: REDIS_CLIENT
      });
      return setTimeout(done, 1800);
    });
    return describe("taggabler_via_redis", function() {
      it("set things up", function(done) {
        thingTagger.set("thing1", ["foo", "bar", "baz"], function(err) {
          should.not.exist(err);
          thingTagger.set("thing2", ["foo"], function(err) {
            should.not.exist(err);
            thingTagger.set("thing3", ["foo", "bar"], function(err) {
              should.not.exist(err);
              done();
            });
          });
        });
      });
      it("should find 3 books from tag foo", function(done) {
        thingTagger.find("foo", function(err, rsp) {
          should.not.exist(err);
          rsp.sort().should.containDeep(["thing1", "thing2", "thing3"]);
          done();
        });
      });
      it("should find 2 books from tag foo and bar", function(done) {
        thingTagger.find(["foo", "bar"], function(err, rsp) {
          should.not.exist(err);
          rsp.sort().should.containDeep(["thing1", "thing3"]);
          done();
        });
      });
      return it("should find 1 books from tag baz", function(done) {
        thingTagger.find("baz", function(err, rsp) {
          should.not.exist(err);
          rsp.sort().should.containDeep(["thing1"]);
          done();
        });
      });
    });
  });

}).call(this);
