// Generated by CoffeeScript 1.6.3
/*
# test for taggabler_via_redis
*/


(function() {
  var REDIS_CLIENT, Taggable, personTagger, should;

  should = require("should");

  Taggable = require("../taggabler_via_redis");

  REDIS_CLIENT = null;

  personTagger = null;

  describe("basic update tests", function() {
    before(function(done) {
      var redis;
      redis = require("redis");
      REDIS_CLIENT = redis.createClient();
      REDIS_CLIENT.flushall();
      personTagger = new Taggable({
        taggable: "person",
        redisClient: REDIS_CLIENT
      });
      return setTimeout(done, 1800);
    });
    return describe("taggabler_via_redis", function() {
      it("should set tags on person", function(done) {
        personTagger.set(21, ["hockey", "basketball", "rugby"], function(err) {
          should.not.exist(err);
          done();
        });
      });
      it("should set tags on second person", function(done) {
        personTagger.set(22, ["hockey"], function(err) {
          should.not.exist(err);
          done();
        });
      });
      it("should change tags first person", function(done) {
        personTagger.set(21, ["cricket", "hockey", "football", "baseball"], function(err) {
          should.not.exist(err);
          done();
        });
      });
      it("should get tags for person", function(done) {
        personTagger.get(21, function(err, tags) {
          should.not.exist(err);
          tags.sort().should.containDeep(["cricket", "hockey", "football", "baseball"].sort());
          done();
        });
      });
      return it("should get hockey as most popular tag", function(done) {
        personTagger.popular(5, function(err, tags) {
          should.not.exist(err);
          tags.length.should.be.below(6);
          tags[0].should.containDeep(["hockey", 2]);
          done();
        });
      });
    });
  });

}).call(this);
