// Generated by CoffeeScript 1.6.3
/*
# test for taggabler_via_redis
*/


(function() {
  var TAGS_COFFEESCRIPT, TAGS_JQUERY, TAGS_NODE, TAGS_RAILS, Taggable, bookTagger, should;

  should = require("should");

  Taggable = require("../taggabler_via_redis");

  bookTagger = new Taggable("book");

  TAGS_NODE = "javascript,server,programming".split(",").sort();

  TAGS_JQUERY = "javascript,client,programming".split(",").sort();

  TAGS_RAILS = "ruby,server,programming".split(",").sort();

  TAGS_COFFEESCRIPT = "javascript,client,server,programmin".split(",").sort();

  describe("test taggabler_via_redis", function() {
    before(function() {});
    return describe("taggabler_via_redis", function() {
      it("should set tags on book 1", function(done) {
        bookTagger.set(1, TAGS_NODE, function(err) {
          should.not.exist(err);
          done();
        });
      });
      return it("should get tags for book 1", function(done) {
        return bookTagger.get(1, function(err, tags) {
          console.log("[taggabler_via_redis_test::method] tags:" + tags);
          should.not.exist(err);
          tags.sort().should.containDeep(TAGS_NODE);
          done();
        });
      });
    });
  });

}).call(this);
